/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'totalCents' : bigint, 'items' : Array<CartItem> }
export interface CartItem {
  'size' : Size,
  'quantity' : bigint,
  'product' : Product,
}
export interface Material {
  'leather' : [] | [string],
  'silk' : [] | [string],
  'polyester' : [] | [string],
  'cotton' : [] | [string],
  'denim' : [] | [string],
}
export interface Order {
  'id' : bigint,
  'totalCents' : bigint,
  'orderTime' : bigint,
  'shippingInfo' : ShippingInfo,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : bigint,
  'collection' : string,
  'name' : string,
  'color' : string,
  'productType' : string,
  'available' : boolean,
  'imageUrl' : string,
  'gender' : string,
  'brand' : string,
  'priceCents' : bigint,
  'sizeRange' : Array<Size>,
  'material' : Material,
}
export interface ShippingInfo {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type Size = string;
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], bigint>,
  'addToCart' : ActorMethod<[bigint, Size, bigint], Cart>,
  'checkout' : ActorMethod<[ShippingInfo], Order>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCart' : ActorMethod<[], Cart>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'queryProducts' : ActorMethod<
    [
      {
        'collection' : [] | [string],
        'productType' : [] | [string],
        'gender' : [] | [string],
        'material' : [] | [string],
      },
    ],
    Array<Product>
  >,
  'removeFromCart' : ActorMethod<[bigint, Size], Cart>,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateCartItem' : ActorMethod<[bigint, Size, bigint], Cart>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];