/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Size = IDL.Text;
export const Material = IDL.Record({
  'leather' : IDL.Opt(IDL.Text),
  'silk' : IDL.Opt(IDL.Text),
  'polyester' : IDL.Opt(IDL.Text),
  'cotton' : IDL.Opt(IDL.Text),
  'denim' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'collection' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'productType' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'gender' : IDL.Text,
  'brand' : IDL.Text,
  'priceCents' : IDL.Nat,
  'sizeRange' : IDL.Vec(Size),
  'material' : Material,
});
export const CartItem = IDL.Record({
  'size' : Size,
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Cart = IDL.Record({
  'totalCents' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const ShippingInfo = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'totalCents' : IDL.Nat,
  'orderTime' : IDL.Int,
  'shippingInfo' : ShippingInfo,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, Size, IDL.Nat], [Cart], []),
  'checkout' : IDL.Func([ShippingInfo], [Order], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'queryProducts' : IDL.Func(
      [
        IDL.Record({
          'collection' : IDL.Opt(IDL.Text),
          'productType' : IDL.Opt(IDL.Text),
          'gender' : IDL.Opt(IDL.Text),
          'material' : IDL.Opt(IDL.Text),
        }),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([IDL.Nat, Size], [Cart], []),
  'seedProducts' : IDL.Func([], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, Size, IDL.Nat], [Cart], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Size = IDL.Text;
  const Material = IDL.Record({
    'leather' : IDL.Opt(IDL.Text),
    'silk' : IDL.Opt(IDL.Text),
    'polyester' : IDL.Opt(IDL.Text),
    'cotton' : IDL.Opt(IDL.Text),
    'denim' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'collection' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'productType' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'gender' : IDL.Text,
    'brand' : IDL.Text,
    'priceCents' : IDL.Nat,
    'sizeRange' : IDL.Vec(Size),
    'material' : Material,
  });
  const CartItem = IDL.Record({
    'size' : Size,
    'quantity' : IDL.Nat,
    'product' : Product,
  });
  const Cart = IDL.Record({
    'totalCents' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const ShippingInfo = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'totalCents' : IDL.Nat,
    'orderTime' : IDL.Int,
    'shippingInfo' : ShippingInfo,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, Size, IDL.Nat], [Cart], []),
    'checkout' : IDL.Func([ShippingInfo], [Order], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'queryProducts' : IDL.Func(
        [
          IDL.Record({
            'collection' : IDL.Opt(IDL.Text),
            'productType' : IDL.Opt(IDL.Text),
            'gender' : IDL.Opt(IDL.Text),
            'material' : IDL.Opt(IDL.Text),
          }),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat, Size], [Cart], []),
    'seedProducts' : IDL.Func([], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, Size, IDL.Nat], [Cart], []),
  });
};

export const init = ({ IDL }) => { return []; };