/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Material {
    leather?: string;
    silk?: string;
    polyester?: string;
    cotton?: string;
    denim?: string;
}
export interface ShippingInfo {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    email: string;
    address: string;
    phone: string;
}
export type Size = string;
export interface Cart {
    totalCents: bigint;
    items: Array<CartItem>;
}
export interface CartItem {
    size: Size;
    quantity: bigint;
    product: Product;
}
export interface Order {
    id: bigint;
    totalCents: bigint;
    orderTime: bigint;
    shippingInfo: ShippingInfo;
    items: Array<CartItem>;
}
export interface Product {
    id: bigint;
    collection: string;
    name: string;
    color: string;
    productType: string;
    available: boolean;
    imageUrl: string;
    gender: string;
    brand: string;
    priceCents: bigint;
    sizeRange: Array<Size>;
    material: Material;
}
export interface backendInterface {
    addProduct(product: Product): Promise<bigint>;
    addToCart(productId: bigint, size: Size, quantity: bigint): Promise<Cart>;
    checkout(shippingInfo: ShippingInfo): Promise<Order>;
    getAllProducts(): Promise<Array<Product>>;
    getCart(): Promise<Cart>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getProduct(id: bigint): Promise<Product | null>;
    queryProducts(filters: {
        collection?: string;
        productType?: string;
        gender?: string;
        material?: string;
    }): Promise<Array<Product>>;
    removeFromCart(productId: bigint, size: Size): Promise<Cart>;
    seedProducts(): Promise<void>;
    updateCartItem(productId: bigint, size: Size, newQuantity: bigint): Promise<Cart>;
}
import type { Cart as _Cart, CartItem as _CartItem, Material as _Material, Order as _Order, Product as _Product, ShippingInfo as _ShippingInfo, Size as _Size } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: Product): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: Size, arg2: bigint): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1, arg2);
                return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1, arg2);
            return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkout(arg0: ShippingInfo): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout(arg0);
                return from_candid_Order_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout(arg0);
            return from_candid_Order_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryProducts(arg0: {
        collection?: string;
        productType?: string;
        gender?: string;
        material?: string;
    }): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryProducts(to_candid_record_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryProducts(to_candid_record_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: bigint, arg1: Size): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0, arg1);
                return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0, arg1);
            return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async updateCartItem(arg0: bigint, arg1: Size, arg2: bigint): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1, arg2);
                return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1, arg2);
            return from_candid_Cart_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CartItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Cart_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Material_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Material): Material {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    collection: string;
    name: string;
    color: string;
    productType: string;
    available: boolean;
    imageUrl: string;
    gender: string;
    brand: string;
    priceCents: bigint;
    sizeRange: Array<_Size>;
    material: _Material;
}): {
    id: bigint;
    collection: string;
    name: string;
    color: string;
    productType: string;
    available: boolean;
    imageUrl: string;
    gender: string;
    brand: string;
    priceCents: bigint;
    sizeRange: Array<Size>;
    material: Material;
} {
    return {
        id: value.id,
        collection: value.collection,
        name: value.name,
        color: value.color,
        productType: value.productType,
        available: value.available,
        imageUrl: value.imageUrl,
        gender: value.gender,
        brand: value.brand,
        priceCents: value.priceCents,
        sizeRange: value.sizeRange,
        material: from_candid_Material_n12(_uploadFile, _downloadFile, value.material)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leather: [] | [string];
    silk: [] | [string];
    polyester: [] | [string];
    cotton: [] | [string];
    denim: [] | [string];
}): {
    leather?: string;
    silk?: string;
    polyester?: string;
    cotton?: string;
    denim?: string;
} {
    return {
        leather: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.leather)),
        silk: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.silk)),
        polyester: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.polyester)),
        cotton: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cotton)),
        denim: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.denim))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalCents: bigint;
    orderTime: bigint;
    shippingInfo: _ShippingInfo;
    items: Array<_CartItem>;
}): {
    id: bigint;
    totalCents: bigint;
    orderTime: bigint;
    shippingInfo: ShippingInfo;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        totalCents: value.totalCents,
        orderTime: value.orderTime,
        shippingInfo: value.shippingInfo,
        items: from_candid_vec_n7(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCents: bigint;
    items: Array<_CartItem>;
}): {
    totalCents: bigint;
    items: Array<CartItem>;
} {
    return {
        totalCents: value.totalCents,
        items: from_candid_vec_n7(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: _Size;
    quantity: bigint;
    product: _Product;
}): {
    size: Size;
    quantity: bigint;
    product: Product;
} {
    return {
        size: value.size,
        quantity: value.quantity,
        product: from_candid_Product_n10(_uploadFile, _downloadFile, value.product)
    };
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Material_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Material): _Material {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    collection: string;
    name: string;
    color: string;
    productType: string;
    available: boolean;
    imageUrl: string;
    gender: string;
    brand: string;
    priceCents: bigint;
    sizeRange: Array<Size>;
    material: Material;
}): {
    id: bigint;
    collection: string;
    name: string;
    color: string;
    productType: string;
    available: boolean;
    imageUrl: string;
    gender: string;
    brand: string;
    priceCents: bigint;
    sizeRange: Array<_Size>;
    material: _Material;
} {
    return {
        id: value.id,
        collection: value.collection,
        name: value.name,
        color: value.color,
        productType: value.productType,
        available: value.available,
        imageUrl: value.imageUrl,
        gender: value.gender,
        brand: value.brand,
        priceCents: value.priceCents,
        sizeRange: value.sizeRange,
        material: to_candid_Material_n3(_uploadFile, _downloadFile, value.material)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    collection?: string;
    productType?: string;
    gender?: string;
    material?: string;
}): {
    collection: [] | [string];
    productType: [] | [string];
    gender: [] | [string];
    material: [] | [string];
} {
    return {
        collection: value.collection ? candid_some(value.collection) : candid_none(),
        productType: value.productType ? candid_some(value.productType) : candid_none(),
        gender: value.gender ? candid_some(value.gender) : candid_none(),
        material: value.material ? candid_some(value.material) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leather?: string;
    silk?: string;
    polyester?: string;
    cotton?: string;
    denim?: string;
}): {
    leather: [] | [string];
    silk: [] | [string];
    polyester: [] | [string];
    cotton: [] | [string];
    denim: [] | [string];
} {
    return {
        leather: value.leather ? candid_some(value.leather) : candid_none(),
        silk: value.silk ? candid_some(value.silk) : candid_none(),
        polyester: value.polyester ? candid_some(value.polyester) : candid_none(),
        cotton: value.cotton ? candid_some(value.cotton) : candid_none(),
        denim: value.denim ? candid_some(value.denim) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
